# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsm < Formula
  desc "Lightweight service mesh for Kubernetes East-West and North-South traffic management"
  homepage "https://flomesh.io/fsm"
  version "1.4.20"
  license "Apache 2.0"

  depends_on "git" => :optional
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flomesh-io/fsm/releases/download/v1.4.20/fsm_v1.4.20_darwin_x86_64.tar.gz"
      sha256 "d4fe4b2707bb1d5b81bc24ea0e7d43277cc1a86f99a6a223f92e0aba4f2759f5"

      def install
        bin.install "fsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flomesh-io/fsm/releases/download/v1.4.20/fsm_v1.4.20_darwin_arm64.tar.gz"
      sha256 "61546152b3ac9dfa575c3d23fe02ba85b3d1ded2fb94df9897bef5a475c290d8"

      def install
        bin.install "fsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flomesh-io/fsm/releases/download/v1.4.20/fsm_v1.4.20_linux_x86_64.tar.gz"
        sha256 "54e5ebfb62d71909a5036ba816d76c182cc33f006d9e6e1553883112406ebdc8"

        def install
          bin.install "fsm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flomesh-io/fsm/releases/download/v1.4.20/fsm_v1.4.20_linux_arm64.tar.gz"
        sha256 "b41b59c927e21d98c29498c4f22295c4cad2626bc86c225110b0176d5e876eb4"

        def install
          bin.install "fsm"
        end
      end
    end
  end

  test do
    system "#{bin}/fsm version"
  end
end
