# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsm < Formula
  desc "Lightweight service mesh for Kubernetes East-West and North-South traffic management"
  homepage "https://flomesh.io/fsm"
  version "1.5.0-alpha.7"
  license "Apache 2.0"

  depends_on "git" => :optional
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flomesh-io/fsm/releases/download/v1.5.0-alpha.7/fsm_v1.5.0-alpha.7_darwin_x86_64.tar.gz"
      sha256 "d9269df40cfceb8ddad94cd32461b1bf2aeaf5899316f4b53424f185543562da"

      def install
        bin.install "fsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flomesh-io/fsm/releases/download/v1.5.0-alpha.7/fsm_v1.5.0-alpha.7_darwin_arm64.tar.gz"
      sha256 "10977b57e25f607d362bbab5c943c17d44ec6fe8087869496f5852657571c63d"

      def install
        bin.install "fsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flomesh-io/fsm/releases/download/v1.5.0-alpha.7/fsm_v1.5.0-alpha.7_linux_x86_64.tar.gz"
        sha256 "0ae7fffbabe3cc7a6caa519f5dcc278f1dd117b995d6a51f4f5f9190cec2a988"

        def install
          bin.install "fsm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flomesh-io/fsm/releases/download/v1.5.0-alpha.7/fsm_v1.5.0-alpha.7_linux_arm64.tar.gz"
        sha256 "9ad8a7556ead4449979251bf5c9cd249faa07609989c3a4d718582d127855b5f"

        def install
          bin.install "fsm"
        end
      end
    end
  end

  test do
    system "#{bin}/fsm version"
  end
end
